spring:
  application:
    name: order-service
  profiles:
    active: dev

management:
  security:
    enabled: false    
     
server:
  port: 9090

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000