spring:
  application:
    name: order-service
  profiles:
    active: dev

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000